# -*- coding: utf-8 -*-
"""Assignment 8. Tensorflow | Nexus | danial022.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ish6R3trjHRWll4tHOhQuHrV2BaJ209B

# 🧠 Assignment: Getting Started with TensorFlow


<p align="center">📢⚠️📂  </p>

<p align="center"> Please name your file using the format: <code>assignmentName_nickname.py/.ipynb</code> (e.g., <code>project1_ali.py</code>) and push it to GitHub with a clear commit message.</p>

<p align="center"> 🚨📝🧠 </p>

------------------------------------------------

## 🎯 Goal
This assignment evaluates your basic skills in using TensorFlow, including creating tensors, performing operations, and building a simple model.

### 1️⃣ Setup and Basics
**Task:**

* Install TensorFlow and verify the version.
* Create a simple tensor and print it.
"""

# Example snippet
import tensorflow as tf

print("TensorFlow version:", tf.__version__)
a = tf.constant([[1, 2], [3, 4]])
print("Tensor a:\n", a)

# Your turn:
# Create a tensor b with values [[5, 6], [7, 8]] and print its shape.

b = tf.constant([[5, 6],
                 [7, 8]])
print("Tensor b:\n", b)

"""### 2️⃣ Tensor Operations
**Task:** Perform element-wise addition and multiplication.
"""

# Example snippet
c = a + b
print("Addition:\n", c)

d = a * b
print("Multiplication:\n", d)

# Your turn:
# Compute a @ b (matrix multiplication) and print the result.

mat_mul = a @ b
print("Matrix Multiplication:\n", mat_mul)

"""### 3️⃣ Random Tensors 🎲
**Task:** Generate a random tensor of shape (3, 3) from a normal distribution and print its mean and standard deviation.
"""

# Example snippet
random_tensor = tf.random.normal([3, 3])
print("Random Tensor:\n", random_tensor)
print("Mean:", tf.reduce_mean(random_tensor))
print("Std Dev:", tf.math.reduce_std(random_tensor))

"""### 4️⃣ Building a Simple Model 🤖
**Task:** Build a single-layer neural network using tf.keras.Sequential.
"""

import tensorflow as tf

model = tf.keras.Sequential([
    tf.keras.layers.Dense(1, input_shape=(1,)),
    tf.keras.layers.Dense(5, activation='relu')
])
model.summary()

# Your turn:
# Add another dense layer with 5 neurons and relu activation.

"""### 5️⃣ Bonus ⚡
* Create a tensor with values from 0 to 9 (inclusive).

* Reshape it to shape (2, 5).

* Pint the reshaped tensor.
"""

# To do
tens = tf.range(10)
reshaped_tens = tf.reshape(tens, (2, 5))
print("Reshaped Tensor:\n", reshaped_tens)

